### ISSUE TITLE
Wrong vignette entry in v0.1 package source on CRAN?

### ISSUE THREAD

**Issue by egnha** [tidyverse/rlang#136]
In the v0.1 package source on [CRAN](https://cran.r-project.org/package=rlang), the vignette is indexed as "Specifying fonts." The offending line is no. 6 in the file tidy-evaluation.Rmd (which I can't find in GitHub master):
```R
  %\VignetteIndexEntry{Specifying fonts}
```
I presume that should be `Tidy evaluation`?

**Comment by lionel-** [comment]
It's been fixed on master.

**Comment by egnha** [comment]
Great, sorry about the false alarm.
