### ISSUE TITLE
R 3.1.0 compatibility

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/rlang#143]
`R_DoubleColonSymbol` seems to be unavailable in R 3.1.0: https://ci.appveyor.com/project/tidyverse/tibble/build/1.0.159/job/4xm3kyip9y3vgty9#L1037

Will submit a PR that tests rlang with R 3.1.0 on AppVeyor.

**Comment by hadley** [comment]
Also need to add 3.1 to travis tests

**Comment by krlmlr** [comment]
@lionel-: We can't use all aspects of rlang in R 3.1.0, I'm getting:

> Warning: declared S3 method 'names.dictionary' not found
> See section 'Generic functions and methods' of the 'Writing R
> Extensions' manual.

Four tests are failing, too, I have fixed them in my f-appveyor branch.

https://ci.appveyor.com/project/krlmlr/rlang/build/1.0.8/job/u552o9gp76gb0fkl#L2265

**Comment by brianrepko** [comment]
hit this as well with dplyr / tibble on 3.1.2
