### ISSUE TITLE
package version mismatch

### ISSUE THREAD

**Issue by tarunparmar** [tidyverse/rlang#145]
Hi, 

I noticed the CRAN version is 0.1 and github one is 0.0.9. 
So confused which one is latest. 

I am having issues with `plogr.h` when I am deploying `purrr` through Rstudio Connect. 

Thx,
Tarun

**Comment by lionel-** [comment]
I see 0.1.9000 which is our development version. See http://r-pkgs.had.co.nz/description.html#version

I should have used 3 components so normally the CRAN version would be 0.1.0 and the dev version would be 0.1.0.9000. Of course the dev version is the latest but it's not a released version yet.
