### ISSUE TITLE
Is there a way to detect an empty quosure?

### ISSUE THREAD

**Issue by Hong-Revo** [tidyverse/rlang#161]
Cf. https://stackoverflow.com/questions/44185933/how-to-detect-an-empty-quosure-in-rlang

```
f <- function(x) enquo(x)

e <- f()
#<quosure: empty>
#~
```
None of these work:
```
> is_empty(e)
[1] FALSE
> is_missing(e)
[1] FALSE
> is_false(e)
[1] FALSE
> is_quosure(e)
[1] TRUE
```

**Comment by lionel-** [comment]
That's `quo_is_empty()`, or `is_empty(get_expr(x))`

**Comment by Hong-Revo** [comment]
I would suggest calling it `is_quo_missing` or `is_missing_quo`, so it appears with the other `is_` functions.

**Comment by lionel-** [comment]
On the other hand with the prefix `quo_is_` it appears with the other `quo_is_` functions.

**Comment by Hong-Revo** [comment]
In that case, they should probably all be renamed. I don't recall the is* idiom being used with a prefix anywhere. There might be some cases where foolish people use a prefix as a product identification/namespacing tool, C-style (cough) but they are foolish.

**Comment by lionel-** [comment]
are you calling us foolish? :/

**Comment by Hong-Revo** [comment]
No, not you....

**Comment by Hong-Revo** [comment]
https://msdn.microsoft.com/en-us/microsoft-r/scaler/packagehelp/rxdistributejob

**Comment by lionel-** [comment]
anyway, we've thought a lot about this naming, it isn't perfect but we are satisfied with it. I think it might need some additional mention in `?quo` for discovery.
