### ISSUE TITLE
symbolize pattern?

### ISSUE THREAD

**Issue by dpastoor** [tidyverse/rlang#163]
Hi, 

In hunting through the source code I was wondering if there is already an equivalent function or pattern to accomplish the following:

I would like to accept either NSE-style names, or reference a variable for programmatic use with !! at the top level of my function:

to do so, I created a function `symbolize` that seems to behave properly with `enexpr`

in the example below, the generated quosure is what I want, but this seems verbose, and not ideal to need to copy around symbolize to where ever I want to use this pattern.

``` r
library(rlang)

symbolize <- function(.x) {
  if (!rlang::is_symbol(.x)) {
    .x <- rlang::sym(.x)
  }
  return(.x)
}


gg_conc_time <- function(df, xvar, yvar) {
  xvar <- symbolize(rlang::enexpr(xvar))
  yvar <- symbolize(rlang::enexpr(yvar))
  rlang::quo(
     ggplot(df, aes(x = !!xvar, y = !!yvar)) + geom_point()
  ) 
}

gg_conc_time(Theoph, Time, conc)
#> <quosure: local>
#> ~ggplot(df, aes(x = Time, y = conc)) + geom_point()

my_time <- "Time"
gg_conc_time(Theoph, !!my_time, conc)
#> <quosure: local>
#> ~ggplot(df, aes(x = Time, y = conc)) + geom_point()
```

Is there a recommended alternative way of accomplishing this?

**Comment by egnha** [comment]
What you're trying to achieve might be easier if you stick to quosures:
```R
```

**Comment by dpastoor** [comment]
That doesn't work - that was one of the first things I tried, based on the dplyr pattern they discuss.

The problem is ~Time and ~conc are quosures, they need to be symbols/names.

Trying to run eval_tidy on that will give you:

```
Don't know how to automatically pick scale for object of type quosure/formula. Defaulting to continuous.
Don't know how to automatically pick scale for object of type quosure/formula. Defaulting to continuous.
Error: Aesthetics must be either length 1 or the same as the data (132): x, y
```

**Comment by dpastoor** [comment]
To show you further - again, why I came up with symbolize - here is just using enexpr, and how it doesn't work with unquoting

``` r
gg_conc_time <- function(df, xvar, yvar) {
    xvar <- rlang::enexpr(xvar)
    yvar <- rlang::enexpr(yvar)
    rlang::quo(
        ggplot(df, aes(x = !!xvar, y = !!yvar)) + geom_point()
    ) 
}

gg_conc_time(Theoph, Time, conc)
#> <quosure: local>
#> ~ggplot(df, aes(x = Time, y = conc)) + geom_point()

# but this doesn't work as the quotes around time remain

my_time <- "Time"
gg_conc_time(Theoph, !!my_time, conc)

# this isn't valid ggplot
#> <quosure: local>
#> ~ggplot(df, aes(x = "Time", y = conc)) + geom_point()
```

**Comment by egnha** [comment]
I see. Then try “flattening” the expression of the quosure and do bare evaluation: `eval(quo_expr(gg_conc_time(Theoph, !!my_time, conc)))` (or `eval_bare()`).

**Comment by dpastoor** [comment]
No, this likewise does not work. You get the exact same as above, with time being quoted as "Time". The point isn't to flatten the quosure (though that is a nice function and I had also tried that prior), its to remove the quotes when you have a quotes inside the resulting quosure `~"Time"`

This is the why I had come up with the symbolize function and was trying to find out if there is an inbuilt function to do that conditional unquoting. It can also be done 'manually' 

```
gg_conc_time(Theoph, !!sym(my_time), conc)
```

but the user experience is quite poor having to type out `!!sym(x)` and will be confusing to users

**Comment by egnha** [comment]
That looks like it might be the solution you're looking for: just call `sym()` directly in `gg_conc_time()`, i.e., replace `symbolize()` with `sym()` in the body of `gg_conc_time()` (as they return the same value on symbols and strings).

**Comment by hadley** [comment]
For this particular case, I think you should just wait until we've implemeneted tidyeval in ggplot2. Then you can just do:

```R
gg_conc_time <- function(df, xvar, yvar) {
  rlang::quo(
     ggplot(df, aes(x = !!enquo(xvar), y = !!enquo(yvar))) + geom_point()
  ) 
}
```

**Comment by dpastoor** [comment]
@egnha no, that also doesn't work! if you try running any of your suggestions they fail - thats the whole point of having implemented symbolize. In the case of your last suggestion, if you `sym()` on something that is already a name, it will fail with an object not found, so then must only use variables or quoted arguments.  Thats why I had gotten to the point of first enexpr-ing and checking then checking if it was was already a symbol (because if it was already and you call sym it will fail) - thus symbolize. 

@hadley the point was to use ggplot as a generalized example, but was supposed to be applicable to any nse-function.  

Sounds like the answer is - there isn't an inbuilt solution to this in rlang. I wonder if a higher-order function could solve this to convert any function into one that accepted parameters in this fashion.

**Comment by hadley** [comment]
@dpastoor I suspect what you want isn't possible and you shouldn't be trying to create this function. @lionel- can probably explain better than I can.

**Comment by lionel-** [comment]
A couple of thoughts:

As @egnha explained, your `symbolize()` function is equivalent to just using `sym()`.

> if you sym() on something that is already a name, it will fail with an object not found

Maybe you're quoting/evaluating at a wrong time? I get:

```r
sym(quote(am))
#> am
```


@egnha is also right that you need to flatten quosures with `quo_expr()` to interface with non-tidyeval functions. You should also set `warn = TRUE` to warn if a quosure was found.

So I would implement your symbolise function like this:

```r
as_sym <- function(.x) {
  sym(quo_expr(.x))
}
```

and use it like this:

```r
as_sym(enexpr(xvar))
```

and if the function you're interfacing with supports tidyeval, I would just use `sym()`.

**Comment by dpastoor** [comment]
@lionel- thanks, your solution works! 

@egnha was helpful in telling some areas to look, though the missing piece from @egnha 's solution was that though using quo_expr, you must also then use sym(), trying to just eval quo_expr as he suggested unfortunately failed, as mentioned above. 

You showed the cleanest combo - so thanks!

here is the final example working as expected with your cleaner as_sym function.

``` r
library(rlang)

as_sym <- function(.x) {
  sym(quo_expr(.x))
}

gg_conc_time <- function(df, .x, .y) {
  .x <- as_sym(enexpr(.x))
  .y <- as_sym(enexpr(.y))
  quo(ggplot(df, aes(x = !!.x, y = !!.y)) +
    geom_point()
  )
}

gg_conc_time(Theoph, Time, conc)
#> <quosure: local>
#> ~ggplot(df, aes(x = Time, y = conc)) + geom_point()
my_var <- "conc"

gg_conc_time(Theoph, Time, !!my_var)
#> <quosure: local>
#> ~ggplot(df, aes(x = Time, y = conc)) + geom_point()
```

is there any reason you can think of, as @hadley thought, that this might be a dangerous pattern? I am just trying to emulate the newer dplyr's ability to have a single function, that can take either type of variable.

**Comment by hadley** [comment]
@dpastoor I don't understand why you want symbols here - the inputs to `aes()` can be expressions. It's also dangerous in general because you're losing the environment information. There's no safe way to do this until we (i.e. @lionel-) updates ggplot2

**Comment by dpastoor** [comment]
@hadley I don't know if I "need" symbols, and would love to know what the better implementation is, and would be more than happy to help expand documentation or anything to pass along distributed knowledge to others - above, I just used ggplot as a tangible example. The pattern I'm looking for is how to implement functions that act like new dplyr api (in that a single interface is available), when the function is then passing parameters to internal functions that only have a NSE interface.

```
library(rlang)

as_sym <- function(.x) {
    sym(quo_expr(.x))
}

my_new_function <- function(df, .x, .y) {
    .x <- as_sym(enexpr(.x))
    .y <- as_sym(enexpr(.y))
    quo(bad_nse_function(df, x = !!.x, y = !!.y))
}

my_new_function(Theoph, Time, conc)
#> <quosure: local>
#> ~bad_nse_function(df, x = Time, y = conc)


my_var <- "conc"
my_new_function(Theoph, Time, !!my_var)
#> <quosure: local>
#> ~bad_nse_function(df, x = Time, y = conc)
```

The symbol seems? to be the only way to get the se/tidy implementation with `my_var` to turn conc into a symbol that the nse function would use. Am I missing something on that?

**Comment by lionel-** [comment]
The main thing to create an API that feels like dplyr is to _evaluate_ expressions, not fiddle with them. As a corollary, each verb should clearly define what types of values it accepts.

For instance `select()` evaluates expressions in a context where data frame columns represent their positions in the data frame. The result should either be column names or column positions, and you can by the same token unquote this kind of objects.

On the other hand `mutate()` expects expressions that evaluate to vectors as long as the data frame (or scalars to recycle). The data frame columns represent the columns themselves. You can unquote vectors of values if they have the right size.

tidyr is a bit different in that you can specify new columns as unquoted symbols. We can't evaluate these expressions since the columns don't exist yet. We're still figuring out if this kind of interface is a good idea (the alternative is to require passing the new column names by string).

**Comment by dpastoor** [comment]
thanks for the explanation @lionel- that was helpful to understand the thought process. I look forward to seeing what patterns you settle on for tidyr as well.
