### ISSUE TITLE
Unexpected interaction between missing and enexpr

### ISSUE THREAD

**Issue by Hong-Revo** [tidyverse/rlang#169]
z <- rlang::missing_arg()

    f <- function(x) if(missing(x)) NULL else rlang::enexpr(x)

    f(z)
    # NULL

`f` works as expected when provided with any other argument, but when there is an object representing a missing argument, and the _name_ of that object is provided as the argument, then it thinks no argument was provided.

If the object `z` contains any other value, or if it doesn't exist at all, then `f` works as expected:

    rm(z)

    f(z)
    # z

    z <- 42

    f(z)
    # z

**Comment by lionel-** [comment]
That behaviour looks right to me. Also `missing_arg()` creates an R missing argument and `missing()` is an R function, so that's outside rlang scope.

**Comment by Hong-Revo** [comment]
Sorry, it looks like this is actually a wart in how base R handles missing values.

Although I should still mention that nothing changes on substituting `is_missing()` for `missing()`; and the behaviour doesn't look right at all. `missing()` (and `is_missing()`) are for checking whether an argument was passed to the calling function. It shouldn't matter what that argument is.

**Comment by lionel-** [comment]
I think there is no wart and everything is working consistently. What do you think should happen?

In general life is more difficult when using missing arguments. In the tidyverse we use `NULL` default arguments to avoid issues.

**Comment by Hong-Revo** [comment]
I think it should return the same result as if I had done `f(f)` or `f(42)` or `f(someNonexistentObject)`. In all these cases, I've supplied something to match the formal argument `x`. The fact that `z` happens to contain something that matches the missing argument shouldn't come into it, because that implies we're looking at the actual value of `z`.

**Comment by lionel-** [comment]
That's just not compatible with the semantics for missing arguments in R, which do return a value that you can inspect. You'll have to analyse the call stack to do this kind of stuff, which is irky territory. I know it's not always possible to avoid dealing with missing values when interfacing with legacy functions, but for new interfaces it's really helpful to use `NULL` default values.

**Comment by Hong-Revo** [comment]
Oh, I'm not suggesting that you should make any changes to rlang. As I said, this is more to do with how base R handles things. If there's any call stack analysis to be done, it should be inside the internals of base::missing.
