### ISSUE TITLE
piping an enexpr/enquo expression breaks is_lang

### ISSUE THREAD

**Issue by Hong-Revo** [tidyverse/rlang#172]
I've come across a sequence where using a pipe with enquo() breaks is_lang(). Following is the minimal piece of code that reproduces the error. Here, f calls g with a pipe in the middle.

``` r
g <- function(a, b) rlang::is_lang(b)

## breaks
f <- function(e)
{
    list() %>% g(rlang::enquo(e))
}
f(list(x=1))
#Error in(function(x, strict=TRUE):
#  the argument has already been evaluated
```

If I don't use the pipe, then the code works:

```r
## works
f2 <- function(e)
{
    g(list(), rlang::enquo(e))
}
f2(list(x=1))
# TRUE
```

If I split the enquo call into a separate statement, then it also works:

```r
## also works
f3 <- function(e)
{
    enquo <- rlang::enquo(e)
    list() %>% g(enquo)
}
f3(list(x=1))
# TRUE
```

I guess this is because of all the language mangling that %>% does? I can work around it, but I'm wondering what else might break in the same way. (I get the same error if I substitute enexpr for enquo, for example.)

**Comment by lionel-** [comment]
It's a known issue that will require changes in magrittr. You can only enquo an argument in its original frame environment, and magrittr evaluates a pipeline in a child.

**Comment by Hong-Revo** [comment]
Do you know if any changes like this are planned for magrittr?

**Comment by lionel-** [comment]
I have a working implementation but the challenge is to support all
magrittr features. I'll try to finish it sometimes this summer.
