### ISSUE TITLE
help - avoid parentheses around spliced parse_exprs 

### ISSUE THREAD

**Issue by mdsumner** [tidyverse/rlang#193]
I'm trying to evaluate a string in a mutate-like function, but the sub-expressions get enclosed in "()" which breaks my function. 

```R
library(rlang)
fun1 <- function(txt) {
  vq <- parse_exprs(gsub(",", ";", txt))
  ## wrap in quo to show effect
  quo(mtcars %>% transmute(!!! vq))
}

exp <- "disp = disp  + 1, a = 2"

fun1(exp)

<quosure: local>
  ~mtcars %>% transmute((disp = disp + 1), (a = 2))
```

The issue is that I really wanted the following as I'm trying to emulate what the user would type under normal circumstances. 

```
  ~mtcars %>% transmute(disp = disp + 1, a = 2)
```

Below is a bit more context,  but hoping the answer is available from this example above. 

Thanks for any help!

I think ultimately the problem is that my function is evaluating the named quosures separately against different tables (that is key to how it works) so I may need another way to go there. That function 'hyper_filter' decomposes the expression with `quos`, then uses the name to match each sub-expression to the right table, evaluates the result with `filter` using the unnamed quosure.  

https://github.com/hypertidy/tidync/blob/master/R/hyper_filter.R#L71-L78

**Comment by lionel-** [comment]
could you provide a complete reprex including inputs please.

**Comment by mdsumner** [comment]
Oops, yes sorry - now reprex.

**Comment by lionel-** [comment]
ok, that's because R parses this as an assignment. You'll have to parse these expressions to extract the names yourself, which shouldn't be very hard. Check that `expr[[1]]` is `=`, then `expr[[2]]` is the name and `expr[[3]]` the rhs.
