### ISSUE TITLE
Compile error R 3.3.3

### ISSUE THREAD

**Issue by aarondigital** [tidyverse/rlang#194]
Receiving compile error when compiling against R 3.3.3 on RHEL 7.2.
`Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/path-to-library/3.3/rlang/libs/rlang.so':
  /path-to-library/3.3/rlang/libs/rlang.so: undefined symbol: R_ExternalPtrAddrFn
`
Fairly new to R libraries so apologies if something I am doing wrong!

Thanks,
Aaron
`

**Comment by lionel-** [comment]
How did you install the package? It looks like it was compiled on R 3.4. In that case, you will need to install rlang from source on your local machine so it gets compiled against R 3.3. You can install from source with:

```r
install.packages("rlang", type = "source")
```

**Comment by aarondigital** [comment]
Still didn't work with type = "source" (I think it was trying to compile anyway) but found install was corrupt and had some mixed versions.  Was definitely this particular installation as reinstalled R and resolved.  Thanks for the pointer as didn't take long after was looking for version probs.  Keep up the good work 👍

**Comment by chrarnold** [comment]
I am facing the same issue and my R installation never had a problem so I am wondering why it happens and how to fix. I deleted ALL packages and tried to freshly reinstall Bioconductor but the same happens early in the installation process. Any ideas?
