### ISSUE TITLE
enquo wrapped a non-function argument

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/rlang#203]
`help(enquo, package='rlang')` states: "enquo() takes a symbol referring to a function argument ..."

So I would expect the following to throw a meaningful exception message, and not to capture something in place of the unbound symbol "`y`". 

``` r
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.1.9000'
packageVersion("rlang")
#> [1] '0.1.1.9000'
rm(list = ls())

(function() mutate(data.frame(x = 1), !!quo_name(enquo(y)) := 2))()
#>   x function (expr) ...
#> 1 1                   2
```

 I am guessing the `quo_name()` is capturing some un-evaluated version of the `enquo(y)`, but this is the notation one must use for left-hand-sides of assignments.  Having `enquo(y)` throw an exception would prevent odd downstream results.

**Comment by hadley** [comment]
The preferred syntax for this is now

```R
(function() mutate(data.frame(x = 1), !!ensym(y) := 2))()
```

But we should figure out what the problem is.

**Comment by JohnMount** [comment]
`ensym` doesn't seem to be exported by the current `CRAN` version of `rlang`.

Moving up to the current dev-version of `rlang` brings in `ensym` (with `ensym()` behavior as desired, but retains the issue with `quo_name(enquo())`).

``` r
suppressPackageStartupMessages(library("dplyr"))
library("rlang")
packageVersion("dplyr")
#> [1] '0.7.1.9000'
packageVersion("rlang")
#> [1] '0.1.1'

(function() mutate(data.frame(x = 1), !!ensym(y) := 2))()
#> Error in ensym(y): could not find function "ensym"
```

``` r
suppressPackageStartupMessages(library("dplyr"))
library("rlang")
packageVersion("dplyr")
#> [1] '0.7.1.9000'
packageVersion("rlang")
#> [1] '0.1.1.9000'

(function() mutate(data.frame(x = 1), !!quo_name(enquo(y)) := 2))()
#>   x function (expr) ...
#> 1 1                   2
(function() mutate(data.frame(x = 1), !!ensym(y) := 2))()
#> Error: Must supply a symbol as argument
```

**Comment by lionel-** [comment]
by the way, I'm thinking that the LHS of `:=` should take the `quo_name()` automatically. This will be consistent with the "name semantics" of some arguments in tidyr (the arguments for specifying new columns).

I think it makes sense to coerce expressions to symbols since that's what we do in the default case, when no name is given.
