### ISSUE TITLE
named quosure "x" special?

### ISSUE THREAD

**Issue by mdsumner** [tidyverse/rlang#205]
I'm using named quosures to dispatch expressions in different contexts, but it seems that "x" is a special name. 

```R
afun <- function(x, ...) {
  quo_named <- rlang::quos(...)
  x
}
d <- tibble::tibble(a = 1:10, b = head(letters, 10))
afun(d, x = index < 2)
# Error in afun(d, x = index < 2) : object 'index' not found
```

I can have a named list of quosures with anything but "x = " for one of them.   Is there a way to approach this that I'm not understanding?

**Comment by lionel-** [comment]
That's because `x` matches your first argument name ;)

We usually prefix argument names with a dot to avoid these argument matching issues.

**Comment by mdsumner** [comment]
Oh duh, sorry. I keep being quite sure about things and then getting confused. Thanks for quick help!
