### ISSUE TITLE
Three more is_ functions to add

### ISSUE THREAD

**Issue by twolodzko** [tidyverse/rlang#216]
rlang has a wide variety of `is_*` functions, I'd add three more functions that I use:

```r
# check if object is a vector but NOT a list
is_simple_vector <- function(x) {
  is.atomic(x) && !is.recursive(x) && !is.array(x)
}

# check if object is a list but NOT a data.frame
is_simple_list <- function(x) {
  is.list(x) && !is.data.frame(x)
}

# wrapper around exists() to check if object is defined
# cf. https://stackoverflow.com/questions/9368900/how-to-check-if-object-variable-is-defined-in-r
is_defined <- function(x) {
  sym <- deparse(substitute(x))
  env <- parent.frame()
  exists(sym, env)
}
```

If you agree, I may prepare a pull with those functions and accompanying documentation and tests.

**Comment by lionel-** [comment]
> is.atomic(x) && !is.recursive(x)

This will always be true. I think you're looking for `is_atomic()`.

> is_simple_list

This is probably `is_bare_list()`, but we won't special case for objects.

> is_defined

You can use `env_has(, "object")`
