### ISSUE TITLE
lazyeval vs rlang?

### ISSUE THREAD

**Issue by gwerbin** [tidyverse/rlang#228]
Not a code issue, but hoping this can be laid out in an FAQ. Maybe I could even help write that FAQ as long as I get an answer for myself :)

What are the different use cases for [`lazyeval`](https://github.com/hadley/lazyeval) and `rlang`?

Is this a fair characterization?
- `rlang` for creating DSLs"
- `lazyeval` is for compiling R code to DSL code?

**Comment by lionel-** [comment]
rlang is a much broader package than lazyeval. It makes more sense to compare the tools provided by the lazyeval package to the tidy eval tools hosted in rlang. Lazyeval and tidy eval are two different answers to the same problem, which is to capture and evaluate code in a structured manner. We will not update or use lazyeval anymore, and we strongly encourage users to switch to tidy eval to create DSLs.
