### ISSUE TITLE
Use case for `is_*` instead of `is.*`?

### ISSUE THREAD

**Issue by gwerbin** [tidyverse/rlang#229]
_Apologies for spamming with two issues at once._

What use does `is_integer` have that `is.integer` doesn't have, and when/why should I use one or the other? I tried reading the documentation and the vignette but it wasn't really enlightening.

Why is `typeof(x) == "integer"` better and "more consistent" than whatever `.Primitive("is.integer")` does? They "operate at a level beneath S3/S4" -- does `.Primitive("is.integer")` just check the S3 class? It seems like the `is.*` primitives do the same thing.

This is the relevant code in R source ([context](https://github.com/wch/r-source/blob/156078a1476df03b964a1cdc2ae8f84182a3675b/src/main/coerce.c#L1796-L1799)):
```c
TYPEOF(CAR(args)) == INTSXP) && !inherits(CAR(args), "factor");
```

which does almost exactly the same thing as `typeof(x) == "integer"`. Here's the source for `typeof` ([context](https://github.com/wch/r-source/blob/156078a1476df03b964a1cdc2ae8f84182a3675b/src/main/coerce.c#L1755-L1759)):
```c
type2rstr(TYPEOF(CAR(args)));
```

Is the idea here just to pretend that typechecking has a single consistent interface and to ignore all the hard-coded "convenience" functions? It seems like these functions express some amount of mistrust or suspicion with respect to R internals. I'm not saying that's a bad idea, just wondering if there's practical benefit to it, or if the benefit is purely psychological.

**Comment by egnha** [comment]
To address just the specific example your raise: `is.integer()` checks that the type is `integer` _and_ that one doesn't have a factor.

(By the way, a very handy tool for looking up the C sources for primitive functions is the [lookup](https://github.com/jimhester/lookup) package by Jim Hester. Try `lookup::lookup(is.integer)`).

**Comment by egnha** [comment]
Concerning `is.integer()`, the answer is in the C source you quote: `is.integer()` checks not only type, but also that one doesn't have a factor (i.e., integer of class `factor`).

**Comment by gwerbin** [comment]
Good point. Is this a fair characterization?

> `is.integer()` operates at the C level, but it still tries to be smart about the "class" of `x` rather than just checking the storage mode. So to some extent it _is_ a mistrust of R internals, in that it exposes them directly and avoids running into any magic or legacy warts in the core implementation.

I see some other oddness in that code as well, e.g.

```c
case 200:           /* is.atomic */
        switch(TYPEOF(CAR(args))) {
        case NILSXP:
            /* NULL is atomic (S compatibly), but not in isVectorAtomic(.) */
```

Has this been taken up with the R core team? It would be great to see some compatibility-breaking  API improvements in R 4.0. How open are they to that kind of thing?

Also: nice tip on `lookup`, thank you!

**Comment by egnha** [comment]
@gwerbin Sorry, I deleted my comment because I seemed to be (unwittingly) just repeating the point you'd already made. But for the record, in case others find it useful, here is the link to the lookup package for reading R source code: https://github.com/jimhester/lookup

**Comment by gwerbin** [comment]
You could have left it. Now it looks like I'm talking to myself!

One final interesting point. I literally just came across a situation where I wanted to check that an object was an integer, but to do so strictly (i.e. exclude factors). `is_integer` is a blind check that the object is stored as an integer, whereas `is.integer` is a strict-ish check that the thing actually _is_ an integer. In this case I wanted the latter. This difference in use case is what needs to be documented clearly, IMO.

**Comment by lionel-** [comment]
`is_bare_integer()` can also be useful. It will return `FALSE` for factors.

**Comment by lionel-** [comment]
> I'm not saying that's a bad idea, just wondering if there's practical benefit to it, or if the benefit is purely psychological.

The benefit is that it makes a clear separation between types and concepts. For instance numeric is a concept while doubles and integers are types, e.g. ways of storing the data. A factor does not fit the numeric concept even though it has a numeric type.

**Comment by lionel-** [comment]
Working with concepts requires genericity by the way, and we try to avoid S3 stuff in rlang.
