### ISSUE TITLE
syms() should take dots

### ISSUE THREAD

**Issue by lionel-** [tidyverse/rlang#235]
for symmetry with `quos()` and `exprs()` etc

**Comment by lionel-** [comment]
And we should have `ensyms()` just like we have `sym()` / `ensym()`.

**Comment by yech1990** [comment]
Hi @lionel- why syms(...) is reveted is in https://github.com/r-lib/rlang/commit/6d798e2585b1c601fe845fb67b744df2125a8fb0

This function is not consistent with `exprs()` and `quos()` , and error prone...

```R
> syms(a, b)
Error in syms(a, b) : unused argument (b)
```

**Comment by lionel-** [comment]
Because it's not at all like `exprs()` and `quos()`, it's not a defusing function.
