### ISSUE TITLE
writing NSE interfaces on top of S4 classes

### ISSUE THREAD

**Issue by sa-lee** [tidyverse/rlang#237]
I'm trying to use rlang to write a `dplyr`-esque backend for some S4 classes in Bioconductor, is there a recommended way to do this?

In the example below I use the `as.env` method to  to coerce my GenomicRanges object to an environment  so I can use `eval_tidy`. I get an error when using `quo` in conjunction with the .data pronoun on secondary slots of the class.

```{r}
library(GenomicRanges)
library(rlang)
gr <- GRanges(Rle(c("chr2", "chr2", "chr1", "chr3"), c(1, 3, 2, 4)),
              IRanges(1:10, width=10:1, names=head(letters, 10)),
              Rle(strand(c("-", "+", "*", "+", "-")), c(1, 2, 2, 3, 2)),
              score=1:10, GC=seq(1, 0, length=10))

# works as expected
eval(quote(strand == "+"), as.env(gr, parent.frame()))

# throws an error, but makes sense
eval_tidy(quo(strand == "+"),  as.env(gr, parent.frame()))
Error in strand == "+" : 
  comparison (1) is possible only for atomic and list types

# if it's in context of data then will evaluate
eval_tidy(quo(.data$strand == "+"),  as.env(gr, parent.frame()))

# throws an error
eval_tidy(quo(.data$score == 1), as.env(gr, parent.frame())
Error: Object `score` not found in environment
get("score",  as.env(gr, parent.frame()))
 [1]  1  2  3  4  5  6  7  8  9 10
```
I'm guessing this is because the `GRanges` class does not define a `[[` method but has accessors for the main slots (`seqnames`, `ranges`, `strand`) and a method for accessing the metadata `mcols`, so when `rlang` coerces the environment to a dictionary it says the object `score` is not found. 

I'm guessing in this case I should write an `as_dictionary` method for GRanges, however it's unclear to me from the documentation as to how actually do this.  Is there a way to construct one without coercing  `GRanges` to a data.frame or a list? 

Any help would be greatly appreciated.

Thanks,
Stuart

**Comment by lionel-** [comment]
How does a GRange get coerced by `as.env(gr, parent.frame())`? Does it become a chain of environments (whose tail has `parent.frame()` as parent) or is it coerced to a single environment (with `parent.frame()` as parent)?

**Comment by sa-lee** [comment]
It's the former, the mcols are stored in the parent of the environment defined by `as.env(gr, parent.frame())`

**Comment by lionel-** [comment]
so you get this?

gr → mcols → parent frame

**Comment by lionel-** [comment]
if you supply an environment to `eval_tidy()`, it's transformed to a dictionary. And during that conversion the environment is taken as a data structure, not as a scope.

You probably want to transform your GR object into an overscope, see `rlang::new_overscope()`. Then use `eval_tidy_()` or `overscope_eval_next()`.

**Comment by sa-lee** [comment]
Ok using the overscope works, with specifying the top to be the parent environment of `as.env(gr_a, parent.frame())`. Thanks for your help.

```{r}
e <- as.env(gr, parent.frame())
overscope <- new_overscope(e, top = parent.env(e))
overscope_eval_next(overscope, quo(score == 1))
overscope_eval_next(overscope, quo(strand == "+"))
```

Thanks for your help.

**Comment by lionel-** [comment]
Great!
