### ISSUE TITLE
Support lists with multiple elements with same names in eval_tidy

### ISSUE THREAD

**Issue by twolodzko** [tidyverse/rlang#239]
```r
list(a = 1, b = 2, a = 3)
```

Is a valid list in R, so the following code should be able to return output for it:

```r
eval_tidy(expr(a + 1), list(a = 1, b = 2, a = 3))
## Error: Data source must be a dictionary
```

**Comment by lionel-** [comment]
Sorry, we require uniquely named elements by design, so you'll have to remove duplicates.
