### ISSUE TITLE
exprs(foo = ) returns empty list

### ISSUE THREAD

**Issue by lionel-** [tidyverse/rlang#240]

**Comment by lionel-** [comment]
It's ignored because it's an empty trailing argument.

@hadley It seems that if an empty argument was supplied with a name, we shouldn't treat it as empty. Does that make sense? That won't affect common cases like `mutate(df, foo, )`

**Comment by hadley** [comment]
Agreed.

**Comment by hadley** [comment]
Duplicate of #286
