### ISSUE TITLE
Change in behavior of eval_bare()

### ISSUE THREAD

**Issue by egnha** [tidyverse/rlang#247]
Could NEWS explain what changed in 0.1.2.9000 to resolve the following incorrect behavior in `eval_bare()`?:

- in 0.1.2, `eval_bare(quote(invisible(0)))` prints `0`
- in 0.1.2.9000, `eval_bare(quote(invisible(0)))` doesn't print anything

(Observed on R 3.4.1)

**Comment by lionel-** [comment]
I don't think anything changed.

**Comment by egnha** [comment]
Hmm, strange. I haven't noticed any change in the code that could have instigated this, either. Are you able to reproduce the results shown? (I get these results on two versions of OS X on different machines, both running R 3.4.1, however.)

**Comment by lionel-** [comment]
I can reproduce.

It's probably the bytecode compiler, 0.1.2 is not compiled but the dev version is. cc @kalibera

**Comment by lionel-** [comment]
@kalibera `eval_bare()` is a simple wrapper around `Rf_eval()`. I think the wrapper shouldn't return invisibly unless it propagates visibility manually (by checking with `withVisible()`).

**Comment by kalibera** [comment]
Would you please have a reproducible example that only uses base/recommended packages? Thanks

**Comment by lionel-** [comment]
I don't think I can find one. The reprex is simple though:

```c
SEXP r_eval(SEXP expr, SEXP env) {
  return Rf_eval(expr, env);
}
```

```r
eval_bare <- function(expr, env = parent.frame()) {
  .Call(r_eval, expr, env)
}

eval_bare(quote(invisible(0)))
```

As `Rf_eval()` sets `R_Visible`, the return value of `eval_bare()` should always be visible.

That's a minor issue, I just thought you'd like to know about it.

**Comment by kalibera** [comment]
I see, this has been fixed by Luke recently - in 73157. The result should be visible because .Call forces visibility. In the current version of R-devel , `withVisible(rlang:::eval_bare(quote(invisible(0))))$visible` is TRUE.

**Comment by lionel-** [comment]
Great, thanks!
