### ISSUE TITLE
make_cnd uses is_scalar_character ; stops calling functions specifying multiple condition types

### ISSUE THREAD

**Issue by m-stanley** [tidyverse/rlang#249]
I'm not sure if this is deliberate or not so I figured I would ask. `make_cnd`'s argument `.cnd` must be a scalar character, so only one type can be specified. This means that every function that uses `make_cnd` can also only specify one additional type.

For example, if in `cnd_abort` if I want to specify two custom types for my error condition, I'm not currently able to do that without providing a condition object as the .cnd parameter rather than a string vector:

```
> cnd_abort(new_cnd(.cnd = c("1", "2"), .msg = "test"))
Error: test
> cnd_abort(c("1", "2"), .msg = "test")
Error: is_condition(.cnd) is not TRUE
```

Is there a good reason for this or can `make_cnd` just be changed?

**Comment by lionel-** [comment]
I think that's fixed on master.
