### ISSUE TITLE
Using functions like `compat_as_lazy()` in other packages?

### ISSUE THREAD

**Issue by juliasilge** [tidyverse/rlang#253]
I want to be able to set up tidytext's functions to use rlang/tidyeval for its inputs and outputs. I notice that in tidyr, for example, there are [whole unexported functions from rlang](https://github.com/tidyverse/tidyr/blob/master/R/compat-lazyeval.R) that are copied and put into that package, including functions like `compat_as_lazy()`. For getting started, I got the functions from [rlang using :::](https://github.com/tidyverse/tidyr/blob/master/R/compat-lazyeval.R), which of course causes a note in R CMD check.

What do you all think about this? If a package like tidytext needs functions like `compat_as_lazy()` or `compat_lazy()`, what do you think is the best way to go about it? Would you consider exporting these functions in the NAMESPACE?

**Comment by lionel-** [comment]
Since this is for deprecated functionality, we just copy the file in each package that needs the compatibility layer.

**Comment by lionel-** [comment]
Maybe we could export them in lazyeval or even in a new package? I'm not sure there would be much benefit as they should be mostly stable.

**Comment by juliasilge** [comment]
So your first inclination is that I just copy all the functions too?

**Comment by lionel-** [comment]
yes :)

**Comment by juliasilge** [comment]
OK! I am a NINJA when it comes to [copy/paste](https://github.com/juliasilge/tidytext/commit/779079958222b5c1d157e319e697076dde124659).
