### ISSUE TITLE
UQ vs !!

### ISSUE THREAD

**Issue by Bart6114** [tidyverse/rlang#256]
From the docs it seems that `UQ` and `!!` are synonyms.

However, check below example:

```
> UQ(quo(name))
<quosure: global>
~name
> `!!`(quo(name))
name
```

Is there something I'm missing or is this a bug?

using: `rlang_0.1.2`

**Comment by lionel-** [comment]
You shouldn't call these functions in non-quoting context. They are exported only to provide documentation points.

The prefix version has been defined as an alias to `UQE()` to be helpful in this situation:

```r
x <- quo(cyl)
expr(mtcars$`!!`(x))
```

For all other purposes, you should use the double operator `!`.
