### ISSUE TITLE
quo examples, don't call the objects quo

### ISSUE THREAD

**Issue by EdwinTh** [tidyverse/rlang#262]
In the examples of `quosure` the output of the `quo` function is called `quo` again several time. Like:

    var <- "foo"
    quo <- quo(var)
    quo

I think this makes the examples harder to follow because you have to keep track wether the function or the object is called. Besides, I don't think its best practise to give objects names that are similar to function names.

**Comment by lionel-** [comment]
> Besides, I don't think its best practise to give objects names that are similar to function names.

I don't think that's true as long as the variables are local. There are many short variable names that make sense such as `expr` or `var` and they often have synonymous functions.

**Comment by EdwinTh** [comment]
It is certainly a matter of taste. The main reason I don't do it in code that is run interactively, is that you get unexpected error messages when the code that creates the variable did not run. See this example:

    > var_name + 4
    Error: object 'var_name' not found
    > var + 4
    Error in var + 4 : non-numeric argument to binary operator

Besides, I prefer that each name only refers to one thing. But again, matter of taste.
