### ISSUE TITLE
Deprecate `!!`() alias to UQE()?

### ISSUE THREAD

**Issue by lionel-** [tidyverse/rlang#278]
It is a bit confusing that `` `!!`() `` is not like `!!`. We could just use `UQE()` directly.

**Comment by lionel-** [comment]
Also `UQE()` should probably use `quo_expr()` rather than `get_expr()` to flatten all quosures. Should it warn when nested quosures are found?

**Comment by hadley** [comment]
But we should keep it as a doc alias in case someone tries `?"!!"`

**Comment by lionel-** [comment]
I now think it should be an alias for `!!`. This is consistent with how R treats operator, e.g. `1 + 2` and `` `+`(1, 2)`` are equivalent. Would such a breaking change be reasonable @hadley? Maybe we should deprecate with warning first.

**Comment by lionel-** [comment]
Also `UQE()` should probably be deprecated in favour of existing tools, e.g. `!! quo_expr(x)`

**Comment by hadley** [comment]
Yeah, that's fine I think.
