### ISSUE TITLE
Unquote-splicing a pairlist may mutate it

### ISSUE THREAD

**Issue by egnha** [tidyverse/rlang#280]
Under 0.1.2.9000 and R 3.4.2, unquote-splicing a pairlist in `quo()` can mutate the pairlist itself.

Example where there should be no side-effects:
```R
x <- pairlist(0)

quo(foo(UQS(x), y))
#> <quosure: global>
#> ~foo(0, y)

x
#> [[1]]
#> [1] 0
#> 
#> [[2]]
#> y
```
The same occurs for `expr()`. `x` is not mutated if it is a list.

(Is the culprit the C function `rlang_interp()`?)

**Comment by lionel-** [comment]
Hmm... This can probably be fixed by adding a `duplicate()` within the R function `UQS()`.

**Comment by egnha** [comment]
Thanks for the workaround.

Nevertheless, do you think this ought to be regarded a bug?

**Comment by lionel-** [comment]
Yes this is a bug, there should be no side effects.
