### ISSUE TITLE
exprs() should preserve named trailing arguments

### ISSUE THREAD

**Issue by hadley** [tidyverse/rlang#286]
``` r
library(rlang)

exprs(x = 1, y = )
#> $x
#> [1] 1
exprs(y = , x = 1)
#> $y
#> 
#> 
#> $x
#> [1] 1
```

This makes it more useful for creating function arguments.

(I think this is probably a general fix for `.ignore_empty` - it should only affect unnamed arguments)

**Comment by hadley** [comment]
Once this change is made, the documentation for `new_function()` needs to be updated to use `exprs()` instead of `alist()`

**Comment by lionel-** [comment]
What should the behaviour be for `"all"`? Maybe we should add `"unnamed"` then, "all" would remove both unnamed and named empty arguments.

Or maybe we should remove this option as it complicates things and isn't very useful. `ignore_empty` would be deprecated and replaced with a bool argument about trailing empty arguments.

**Comment by hadley** [comment]
The behaviour would that we only ever drop unnamed arguments. I think that's inline with the original intent.
