### ISSUE TITLE
CRAN has wrong namespace file

### ISSUE THREAD

**Issue by tjmahr** [tidyverse/rlang#288]
One of my packages that imported `ensym()` no longer works because the package (installed from CRAN) no longer exports the function.  

Looking at the [CRAN-mirror](https://github.com/cran/rlang) and source file from the CRAN page, it looks like CRAN has the wrong namespace file

![image](https://user-images.githubusercontent.com/1890315/32617507-c821122a-c53a-11e7-8cff-8166d8250315.png)

**Comment by lionel-** [comment]
There were no new function exported since version 0.1.1. `ensym()` is only in the development version.

**Comment by tjmahr** [comment]
Oops. I saw that the last CRAN release was a few days ago and assumed that it was exported. Sorry about that.

**Comment by lionel-** [comment]
no worries!
