### ISSUE TITLE
Fix parse tree for !!

### ISSUE THREAD

**Issue by lionel-** [tidyverse/rlang#296]
* Remove one layer of parentheses surrounding bang-bang, e.g. `(!! x)`. This way:

```r
x <- quote(fn)
expr(
  (!! x)(foo)
)

# expands to:
fn(foo)

# instead of:
(fn)(foo)
```

* What operator precedence do we want for `!!`? On master it's now binding very tightly, but maybe we should make some exceptions. Maybe operators that are written without space should bing tightlier than `!!`:

```r
expr(!! x:y)
```

Currently on master this is equivalent to:

```r
expr((!! x):y)
```

But maybe this should be:

```r
expr(!! (x:y))
```

There is a similar issue for `^`:

```r
expr(!! x^y)
```

**Comment by hadley** [comment]
I think it's most consistent to match the existing infix operators `+` and `-`
