### ISSUE TITLE
parse trees and AST's

### ISSUE THREAD

**Issue by dan87134** [tidyverse/rlang#298]
A parse tree and an AST are different things.

In this doc ( http://rlang.tidyverse.org/reference/pairlist.html ) you say that expressions are structured as parse trees, but in the upcoming version of ADV-R Hadley says they are AST's. It would be good if this doc and ADV-R agreed on terms since they are both specifically tidyverse documents. 

The Wikipedia article this doc refers to ( https://en.wikipedia.org/wiki/Parse_tree  ) specifically says that a parse tree is **not** an AST and they are not used in computer programing. 

*Parse trees concretely[clarification needed] reflect the syntax of the input language, making them distinct from the abstract syntax trees used in computer programming*

So it is at least confusing, even is they don't know any computer science, if someone digs a bit further into the links provided after reading ADV-R and ends up reading the Wikipedia article... I know it confused me :-)

And, even though I am not a "language theorist" :-), from looking at how enquo and friends work it looks to me like R structures expressions as AST's (I don't see how it could work otherwise) not parse trees. Here is an example:

``` r
suppressPackageStartupMessages(library(tidyverse))
# this arithmetic expression should evalualate
# "a * b" and "c * d" before adding them
q1 <- quo(a * b + c * d)
# and in fact it does, because it is parsing into the behavior,
# not just concrete syntax, by making + the head, i.e. the function,
# and a * b and c * d the arguments.
#
# If R were just parsing the  concrete syntax "*" would be the head
# and the tail would include "a * b + c" and "d" as arguments.
#
# in the next example 
q2 <- quo((a + b))
rlang::lang_head(q2)
#> `(`
rlang::lang_tail(q2)
#> [[1]]
#> a + b
#
# The "(" is made the function even though the wikipedia
# article specifically says that an AST would not include
# things like "(". However in R "(" is a function, not just
# syntax so it makes sense to include it in an AST
```

Note the parse tree Wikipedia article refers to ast's here https://en.wikipedia.org/wiki/Abstract_syntax_tree

**Comment by lionel-** [comment]
hmm I think that in lisp-like languages the AST and the parse tree are the same thing, e.g. https://en.wikipedia.org/wiki/Homoiconicity. Oh I see that they mention Julia but not R :/

**Comment by dan87134** [comment]
I've never programmed in Lisp but I think that in Lisp the parse tree and the AST would be the same becauseI don't think Lisp assumes any semantics for symbols like "+" and "*" like R does. The first example showed points out that R does assume the semantics, i.e.  precedence, of "+" and "*".

What the article is saying (IMHO of course :-) ) is that Lisp is sort of unique in that the parse tree for the language and the AST are the same.  So in Lisp to get conventional precedence you need to do (a + b) * (c + d) where in R a + b *  c + d works just fine. Maybe that's why some think Lisp means "lost in silly parentheses" :-)

**Comment by lionel-** [comment]
If anything, code in R is represented as a parse tree and not as an AST. An AST would not include all the extra parentheses here: `quote(((((1))))`. In R it has to because it can't assume any semantical meaning to syntactic elements:

```r
x <- quote(((((1)))))

eval(x, list(`(` = function(x) x + 1))
#> [1] 5
```

I think the agnosticity of syntax elements regarding semantics is part of homoiconicity and treating code as data. E.g. in lisp the parser doesn't know whether a parenthetical grouping is a list or a function call. Not sure if AST is then a correct term for lisp-like languages (including R) because it looks like you cannot abstract out the concrete syntax tree.

**Comment by dan87134** [comment]
We've probably spent more brain cells on this than it's worth but...

I think that in fact what R is building is an AST, not a parse tree. But it any case it seems all the tidyverse doc's should use the same terminology.

I'm just pointing out what I see...

A parse tree cannot parse an expression a * b + c  * d and take into account operator precedence. The wikipedia article on parse trees mentions that a parse tree can only be used for a context- free grammar. But a context-free grammar does not do look ahead and taking into account operator precedence would require that.

In the case of parentheses, even though the wikipedia AST article says "(" is not included in an AST that isn't the case for R. In R "(" is a function that can be overridden, unlike languages like C, C++ or even .NET, "(" where it is a piece of syntax so when the AST is built for one of those languages  parentheses are thrown away.  In those languages you cannot overload "(".

You can really write an expression like a * b + c * d in Lisp... or on the HP RPN calc's that Hadley mentions, I used to use one :-) You have to be completely specific about grouping things with parens.

Here is how R parses a * b + c * d

``` r
q2 = rlang::quo(a * b + c * d)
# the head is "+"
rlang::lang_head(q2)
#> `+`
rlang::lang_tail(q2)
# the tail is "a * b" and "c * d"
#> [[1]]
#> a * b
#> 
#> [[2]]
#> c * d
```

Notice that the head is "+".  That's because is taking into account operator precedence. A parse tree couldn't do that.

mythical parse tree would produce this
NOT REAL CODE, just PowerPoint code :-)
`q3 = rlang::quo(a + b * c + d)`
`rlang::lang_head(q3)`
`#> +`
`rlang::lang_tail(q3)`
`#> [[1]]`
`#> a * b + c`
`#>` 
`#> [[2]]`
`#> d`

**Comment by lionel-** [comment]
> But a context-free grammar does not do look ahead and taking into account operator precedence would require that.

Context-free grammars can and do involve operator precedence (there are examples in the wiki article). Parse trees are typically built taking operator precedence into account.

**Comment by lionel-** [comment]
I you are right. A parse tree would include `else` and `in` operators, but these are absent of the AST that is returned by the parser.

**Comment by dan87134** [comment]
Thanks for keeping me updated @lionel-
