### ISSUE TITLE
C API for signaling conditions

### ISSUE THREAD

**Issue by jimhester** [tidyverse/rlang#31]
There isn't currently a way to signal a custom condition from C, it would be nice to define functions in rlang to do so. If they are header only and included in `inst/include` they can be used from other packages by `LinkingTo: rlang`.

**Comment by lionel-** [comment]
One thing on my todo list is a patch to make the condition API public. I found a way to register handlers locally, so in addition to C-level signal functions, we'll be able to get rid of the crazy recursive stack traces (e.g. `tryCatch()`, `tryCatchList()`, `tryCatchOne()`, etc).

**Comment by hadley** [comment]
Regardless of whether or not that patch is successful, we'll also need a local implementation so that the tidyverse (which will only depend on R 3.1.0) can use it.

**Comment by lionel-** [comment]
Unfortunately I don't think that's possible without making `Internal()` calls, so we'll have to resort to the recursive implementation on old releases of R.

**Comment by hadley** [comment]
We might just have to call R from C

**Comment by lionel-** [comment]
ah yes sorry, I was talking about `with_handlers()`
