### ISSUE TITLE
v0.1.6 Issues 

### ISSUE THREAD

**Issue by TuSKan** [tidyverse/rlang#329]
devtools:
call: .Call(rlang_interp, body(x), env %||% fn_env(x), TRUE)
  error: Incorrect number of arguments (3), expecting 2 for 'rlang_interp'

readr:
Error in read_tokens_(data, tokenizer, col_specs, col_names, locale_,  : 
  Evaluation error: Incorrect number of arguments (3), expecting 2 for 'rlang_interp'.

**Comment by lionel-** [comment]
Do you use Windows? In that case could you reinstall rlang in a fresh session please? The DLL doesn't get updated if the package is already loaded during installation.

**Comment by TuSKan** [comment]
You are right!, Sorry for that.
