### ISSUE TITLE
Remove data mask cleaning

### ISSUE THREAD

**Issue by lionel-** [tidyverse/rlang#382]
To simplify tidy eval. Will cause subtle obscure bugs due to quosure self-evaluation when the data mask env escapes (e.g. when creating a function within `dplyr::do()`) but they should be rare and go away when we switch to thunk implementation of quosures.

**Comment by krlmlr** [comment]
Can we do this after switching to thunk implementation, to avoid those obscure bugs?

**Comment by lionel-** [comment]
we can remove the `~` binding but then people creating a data mask manually will have to clean by themselves which requires either documentation or an exported function. cc @hadley.

I think the bug would be really rare, people would have to create and save a function with `do()` and that function would have to unquote quosures for the bug to appear (unless I'm missing something).

**Comment by hadley** [comment]
@krlmlr dplyr can do cleaning by hand to avoid any problems in the interim.

**Comment by krlmlr** [comment]
I'm not aware of the details, only concerned that something like krlmlr/bindrcpp#2 can happen again.

**Comment by lionel-** [comment]
Actually this is also going to affect functions like `purrr::rerun()` even though this kind of function doesn't use any auxiliary data. Until we switch to the thunk implementation we need to evaluate quosures in a minimalistic data mask with a `~` binding for self-evaluation. Even though this `~` binding only affects quosures, not simple formulas, Kirill has a point that this is a bit too dangerous.

Note that we won't be able to switch to a thunk impl right away because of the base R printer bug where calls with a class are evaluated on printing (which isn't a problem for formula-based quosures since they self-quote under base evaluation).

So maybe it's better to keep `data_mask_clean()` and mark it as "maturing" rather than "stable". It would take an argument to specify the kind of cleaning, one of `c("tilde", "rechain", "wipe")`. Rechaining should be fast, wiping bindings is the current slow implementation.

Also after thinking about it more, I'm pretty sure we do need to create a minimalistic mask for each nested quosure so objects escaping from those inherit from their original lexical context and not the `env` argument of `eval_tidy()`.

**Comment by lionel-** [comment]
> I'm not aware of the details, only concerned that something like krlmlr/bindrcpp#2 can happen again.

Unless someone goes out of their way to capture the parent environment of the data mask, this shouldn't happen. Rechaining should be safe enough. Also JJ mentioned on Slack that the xptrs can be set to point to `NULL` and then R will give a runtime error instead of crashing.

**Comment by hadley** [comment]
Can you give an example of how that problem might reveal itself with `rerun()`?

**Comment by lionel-** [comment]
> Can you give an example of how that problem might reveal itself with rerun()?

I can't find realistic/meaningful examples. Let's try without any cleaning then.


About environment escaping from nested quosures: the idea of creating minimalistic masks for nested quosures so that escaping formulas/closures inherit from their lexical scope will not work if we keep the mask objects alive. We'd have to either:

- Recreate a full mask for each nested quosure. This is too expensive without mirror environments and we shouldn't use those unless they become official part of the R API. I don't know if that is possible because I'm not sure what are the implications of mirror envs for the GC. This is probably something worth exploring in the future.

- Use environments with two parents. That would require objectables and might degrade performance of tidy eval functions.

So for now environment escaping the data mask will always inherit from the `env` argument of `eval_tidy()` rather than the original quosure env.
