### ISSUE TITLE
Issues with splicing and unquoting within `call_modify`

### ISSUE THREAD

**Issue by vspinu** [tidyverse/rlang#392]
`splice` is not recognized within `call_modify` and unquoting doesn't work with pairlists:

```R

> call_modify(pairlist(a=3), !!!fn_fmls(plot))
Error: Can.t use `!!!` on atomic vectors in non-quoting functions
> call_modify(pairlist(a=3), splice(fn_fmls(plot)))
$a
[1] 3

[[2]]
[[2]][[1]]
[[2]][[1]]$x
[[2]][[1]]$y
[[2]][[1]]$...

> call_modify(pairlist(a=3), !!!as.list(fn_fmls(plot)))
$a
[1] 3
$x
$y
$...
```

(related to #369 but different)

**Comment by lionel-** [comment]
> call_modify(pairlist(a=3), splice(fn_fmls(plot)))

I get the expected error message about splicing only working on lists.

> call_modify(pairlist(a=3), !!!as.list(fn_fmls(plot)))

That seems to give the desired output.

`call_` functions are not really supposed to be used on pairlist though.

**Comment by vspinu** [comment]
> I get the expected error message about splicing only working on lists.

Hm. Looks like interaction with purrr plays a role here:

```R

> library(rlang)
> library(purrr)
> call_modify(pairlist(a=3), splice(fn_fmls(plot)))
$a
[1] 3
[[2]]
[[2]][[1]]
[[2]][[1]]$x
[[2]][[1]]$y
[[2]][[1]]$...
```
> That seems to give the desired output.

Yes. Included there to demonstrate the expected output when a list is supplied. 

> call_ functions are not really supposed to be used on pairlist though.

It's just an example but would be nice to have similar functionality on pairlists. In my project I am manipulating argument lists, not calls. Would aliasing `pairlist_modify` to `call_modify` be an option?

**Comment by lionel-** [comment]
>  Looks like interaction with purrr plays a role here:

Ah yes there's a `splice()` function in purrr, that must be it.


> It's just an example but would be nice to have similar functionality on pairlists.

I think any pairlist API will remain private for now.

**Comment by vspinu** [comment]
One issue remains:

```R
> call_modify(pairlist(a=3), !!!fn_fmls(plot))
Error: Can.t use `!!!` on atomic vectors in non-quoting functions
```

Or is this identical to #369? It shows different message.

**Comment by lionel-** [comment]
> Or is this identical to #369? It shows different message.

Ah yes, it's a different message because detected in the C tidy dots logic.
